/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ControllerConsole_Controller */

#ifndef _Included_ControllerConsole_Controller
#define _Included_ControllerConsole_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_open
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_ControllerConsole_Controller_controller_1open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_controller_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_get_value
 * Signature: (JII)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_controller_1get_1value
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    controller_set_value
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_controller_1set_1value
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    module_add
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_module_1add
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    iochannel_add
 * Signature: (JILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_iochannel_1add
  (JNIEnv *, jobject, jlong, jint, jstring, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_add
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_obit_1add
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_add
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_opulse_1add
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     ControllerConsole_Controller
 * Method:    iochannel_get_value
 * Signature: (JII)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_iochannel_1get_1value
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    iochannel_set_value
 * Signature: (JIIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_iochannel_1set_1value
  (JNIEnv *, jobject, jlong, jint, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    iochannel_pulse
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_ControllerConsole_Controller_iochannel_1pulse
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ochannel_write
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_ochannel_1write
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_get_value
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_obit_1get_1value
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    obit_set_value
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_obit_1set_1value
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_get_value
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_opulse_1get_1value
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_set_value
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_opulse_1set_1value
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     ControllerConsole_Controller
 * Method:    opulse_out
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_ControllerConsole_Controller_opulse_1out
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ControllerConsole_Controller
 * Method:    ichannel_read
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_ControllerConsole_Controller_ichannel_1read
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
